import type { LevelCode } from "@/types/database";

/**
 * Phrases courtes tirées du corpus des histoires (mêmes critères que la
 * dictée : longueur bornée par niveau), utilisées pour le jeu Satzbau-
 * Puzzle — remettre les mots dans le bon ordre.
 */
export const SATZBAU_SENTENCES: Record<LevelCode, string[]> = {
  A1: [
    "Alle sind wieder glücklich.",
    "Die Kinder essen davon.",
    "König Ludwig der Zweite liebt Märchen.",
    "Sophie hat neue Mitschüler.",
    "Später wird er ein berühmter Wissenschaftler.",
    "Die Menschen essen Brezeln und Wurst.",
    "Albert stellt viele Fragen.",
    "Der Vater ist stolz auf ihn.",
    "Ihre Besitzer wollen sie nicht mehr.",
    "Die Eltern sind stolz.",
    "Der Junge trinkt eine Tasse Tee.",
    "Meine Schwester lernt Deutsch.",
    "Wir kaufen frisches Brot.",
    "Das Wetter ist heute schön.",
    "Er hat einen neuen Hund.",
  ],
  A2: [
    "Die Wartburg kann man auch heute besuchen.",
    "Danach studierte er Physik in Zürich.",
    "Danach haben sie zusammen dem Weihnachtsmann zugeschaut.",
    "Er teilte freundlich sein Brot mit ihm.",
    "Dort gab es viele alte Bücher.",
    "Das Konzert hat um 19 Uhr begonnen.",
    "Die Entdeckung war eine Sensation.",
    "Er interessierte sich sehr für das Fliegen.",
    "Dort hat sie alte Instrumente gesehen.",
    "Die Stiefmutter erlaubte Aschenputtel nicht mitzukommen.",
    "Nach der Schule spielt sie Fußball.",
    "Am Wochenende besuchen wir unsere Großeltern.",
    "Der Zug fährt pünktlich ab.",
    "Sie hat gestern einen Brief geschrieben.",
    "Im Sommer fahren wir ans Meer.",
  ],
  B1: [
    "Er hatte es sicherheitshalber hinter der Theke aufbewahrt.",
    "Einige hatten fast nur Positives geschrieben.",
    "Ihre Lehrerin lobte am Ende besonders diesen Gedanken.",
    "Seine Eltern reagierten unterschiedlich auf die schlechte Note.",
    "Wütend ließ Gessler ihn festnehmen.",
    "Diese kleine Stelle blieb ungeschützt.",
    "Sarah fühlte sich danach viel sicherer.",
    "Seitdem findet das Fest fast jedes Jahr statt.",
    "Felix hörte aufmerksam zu und ermutigte ihn.",
    "Doch die politische Lage in Deutschland veränderte sich.",
    "Obwohl es regnete, ging er spazieren.",
    "Die Firma sucht dringend neue Mitarbeiter.",
    "Er hat sich für das Praktikum beworben.",
    "Nach langem Zögern traf sie die Entscheidung.",
    "Die Ausbildung dauert normalerweise drei Jahre.",
  ],
  B2: [
    "Doch die Regelmäßigkeit beunruhigte ihn zunehmend.",
    "Diese Lösung erschien Anna deutlich weniger riskant.",
    "Um Mitternacht erreichte der Sturm seinen Höhepunkt.",
    "Zuerst wurde er nur übersehen.",
    "Eines Morgens war der Kiosk geschlossen.",
    "Auf dem Elternabend kam es zum Streit.",
    "Am Hunnenhof entlud sich Kriemhilds jahrelanger Zorn.",
    "Sie sprachen zwanzig Minuten lang.",
    "Er hielt ein kleines Bündel in der Hand.",
    "Der Höhepunkt dieser Ambition war zugleich ihr Ende.",
    "Trotz aller Bemühungen scheiterte das Projekt.",
    "Die Regierung kündigte neue Maßnahmen an.",
    "Ohne seine Hilfe wäre es unmöglich gewesen.",
    "Die Debatte dauerte bis spät in die Nacht.",
    "Viele Experten bezweifeln diese Prognose.",
  ],
  C1: [
    "Bei genauerer Betrachtung erscheint mir diese Lesart jedoch zu einfach.",
    "Am Anfang empfand ich das als bedrückend.",
    "Ich teile diese Sorge nur teilweise.",
    "Das Gegenteil scheint der Fall gewesen zu sein.",
    "Der Sommer verging in einer merkwürdigen Schwebe zwischen Scham und Erleichterung.",
    "Kriemhild erschlug ihn daraufhin mit dem eigenen Schwert Siegfrieds.",
    "Auf dem Wartebildschirm wurde 41 angezeigt.",
    "Diese Ambivalenz begleitet mich in meinem eigenen Beruf.",
    "Diese Erkenntnis veränderte seine Wahrnehmung des urbanen Lebens grundlegend.",
    "Diese Entwicklung wirft grundlegende ethische Fragen auf.",
    "Der Autor hinterfragt gesellschaftliche Normen kritisch.",
    "Angesichts der Umstände blieb ihm keine Wahl.",
    "Die Studie widerlegt frühere Annahmen eindeutig.",
    "Seine Argumentation überzeugte selbst die Skeptiker.",
  ],
  C2: [
    "Ihr Bruder spricht nicht mehr darüber.",
    "Nur wenige Menschen hatten Zugang zu all diesen Einzelheiten gehabt.",
    "Die Konferenz gewährte eine Nachprüfung im August.",
    "Wie er über einer einzigen Fermate eine ganze Nacht saß.",
    "Sie selbst erzählt die Geschichte niemandem mehr.",
    "Die Grenzen zwischen Fiktion und Realität verschwimmen zunehmend.",
    "Eine erschöpfende Antwort auf diese Frage steht noch aus.",
    "Der Text entzieht sich einer eindeutigen Interpretation.",
    "Diese Beobachtung relativiert die vorherige These erheblich.",
    "Kaum jemand ahnte das Ausmaß der Krise.",
  ],
};
